name: Go AWS nitro enclave attestation document authentication module

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Check formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then gofmt -d .; exit 1; fi;

      - name: Build
        run: go build 

      - name: Test
        run: go test
