name: Cert Verifier Audit

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual runs

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Cache HTTP GET responses
        uses: actions/cache@v4
        with:
          path: /tmp/http-get-cache
          key: ${{ runner.os }}-http-cache-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-http-cache-

      - name: Run cert verifier audit
        id: audit
        continue-on-error: true
        env:
          VERIFIED_HOST_NAME: verified.teels.dev
        run: go run cert_verifier/cert_verifier.go audit
        
      - name: Retry cert verifier audit if the first attempt failed
        if: steps.audit.outcome == 'failure'
        env:
          VERIFIED_HOST_NAME: verified.teels.dev
        run: go run cert_verifier/cert_verifier.go audit
      
      - name: Check if host is up
        id: check-host
        run: |
          if curl -s -o /dev/null -w "%{http_code}" https://verified.teels.dev/formatter | grep -q "200"; then
            echo "host_up=true" >> $GITHUB_OUTPUT
          else
            echo "host_up=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run cert verifier live check
        if: steps.check-host.outputs.host_up == 'true'
        env:
          VERIFIED_HOST_NAME: verified.teels.dev
        run: go run cert_verifier/cert_verifier.go live 